[project]
name = "git-summitagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic-ai>=0.1.8",
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.29.0",
]
